version: '3.8'

services:
  app:
    image: book-point_mvp
    build:
      context: .
#    restart: on-failure
    container_name: book-point-app
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_NAME: bookPoint
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db

  db:
    image: postgres:15
#    restart: on-failure
    container_name: pgsql
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop