services:
  db:
    image: postgres:15
#    restart: on-failure
    container_name: pgsql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop