#security:
#  rules:
#    - paths:
#        - /api/public/**
#        - /api/health/**
#        - /api/status/**
#      method: ALL
#      roles: permitAll
#    - paths:
#        - /api/admin/**
#        - /api/config/**
#      method: POST
#      roles: ADMIN
#    - paths:
#        - /api/user/**
#      method: GET
#      roles: USER,ADMIN